### ISSUE TITLE
Allow contracts to subscribe to other contracts

### ISSUE THREAD

**Issue by sanity** [freenet/locutus#132]
Allow contracts to follow or subscribe to other contract states, the contracts state can be modified in response to the state and state changes of other contracts.

This should open up a wide variety of use cases and will bring Locutus closer to being a general-purpose decentralized computation platform.

**Comment by iduartgomez** [comment]
Closing this for now as we are not clear on the mechanism of this and it would pose several problems we don't know how to solve yet.
