### ISSUE TITLE
send update doesn't work

### ISSUE THREAD

**Issue by kakoc** [freenet/locutus#207]
Commit: f363ec1d26486dac959e05d99e393cd63ee8b104
Platform: m1 Monterey
Problem with steps:
Copying index, state html from root into contracts/freenet_microblogging_web/web
Then running the following script 
```
#!/usr/bin/bash

# clean locutus temp_dir
rm -rf /var/folders/4g/x2ybv6lj4s794_j2w41d6j_r0000gn/T/locutus/

cd crates/http-gw/examples
rm freenet_microblogging_data
rm freenet_microblogging_data.wasm
rm freenet_microblogging_web
rm freenet_microblogging_web.wasm
cd ../../..

cargo build	

cd contracts/freenet-microblogging-web
bash compile_contract.sh 	
mv ./freenet_microblogging_web.wasm ../../crates/http-gw/examples/
cd ../..

cd contracts/freenet-microblogging-data
bash compile_contract.sh 	
mv freenet_microblogging_data.wasm ../../crates/http-gw/examples/
cd ../..

cd crates/locutus-dev
cargo run --bin build_state -- --input-path ../../contracts/freenet-microblogging-web/web --output-file ../http-gw/examples/freenet_microblogging_web --contract-type web
cargo run --bin build_state -- --input-path ../../contracts/freenet-microblogging-data --output-file ../http-gw/examples/freenet_microblogging_data --contract-type data
cd ../..

cargo run --example contract_browsing --features local
```

Then replacing DATA_CONTRACT with the new key(state.html file)
Then opening localhost: `127.0.0.1/<key>/state.html`
State page is displayed, ws established
Clicking on `Send Update` button
Browser dev tools show:
```
Sending: [{"author":"IDG","date":"2022-06-15T00:00:00Z","title":"New msg","content":"..."}]
state.html:74 Update response: {"err":"client error: unhandled error: RuntimeError: unreachable","result":"error"}
```
I tried to figure out the place where it crashes and it appears here:
https://github.com/freenet/locutus/blob/f363ec1d26486dac959e05d99e393cd63ee8b104/crates/locutus-runtime/src/runtime.rs#L386

I verified that summary_func is valid(summary_func.is_ok())
So it crashes on call
I tried print an error instead of unwrapping and got that: 
```
    RuntimeError {
        source: Trap(
            UnreachableCodeReached,
        ),
        wasm_trace: [],
        native_trace:    0:        0x100de36d4 - <unknown>
           1:        0x100de3b50 - <unknown>
           2:        0x100a3ebbc - <unknown>
           3:        0x100a3ea08 - <unknown>
           4:        0x100dd3d9c - <unknown>
           5:        0x18e5e44e4 - <unknown>
        ,
    },
)
```

**Comment by iduartgomez** [comment]
Yes I am aware of this, broke in one of the last changes, the problem is probably internal to the contract. Take in mind `main`branch is a WIP now and things are not guaranteed to work, but planning to leave it in a working state ASAP.

**Comment by iduartgomez** [comment]
@kakoc I changed the structure of were the contracts are placed a bit, if you want to create a PR for the script to build the sample contracts is welcome. It can be placed under `.../contracts/freenet-microblogging`

**Comment by kakoc** [comment]
> @kakoc I changed the structure of were the contracts are placed a bit, if you want to create a PR for the script to build the sample contracts is welcome. It can be placed under `.../contracts/freenet-microblogging`

Cool! I'll tackle on it.

**Comment by iduartgomez** [comment]
All this should be working and fixed now and the updates should show in the browser too.
