### ISSUE TITLE
Locutus over Tor/Arti or I2P

### ISSUE THREAD

**Issue by Destroyinator69420** [freenet/locutus#253]
It would massviely improve the privacy of Locutus if users could opt in to running locutus over Tor/I2P. Once the Tor project finishes Arti, Tor could be integrated directly into Locutus, since arti is written in rust. I2P features a protocol called SAM to facilitate communication between I2P, which is written in Java, and applications written in other langauges. There is a SAM client Library written in Rust on this github repo. (https://github.com/i2p/i2p-rs) Arti is currently on version 0.6.0, and they are aiming for version 1.0 in the future. (https://blog.torproject.org/arti_060_released/)

**Comment by sanity** [comment]
Locutus is designed to be an efficient decentralized low-level protocol, so running it over another much more centralized protocol like Tor wouldn't make sense.

It would make more sense to implement an onion routing service on top of Locutus.
