### ISSUE TITLE
Components: A secret management system

### ISSUE THREAD

**Issue by sanity** [freenet/locutus#283]
*Note: Previously, the term "component" referred to imported JavaScript libraries distributed like applications - this proposal changes that definition.*

The role of the Component system is to manage the use of secret information such as private keys. A Component is WebAssembly code that implements the Component interface described below. These Components execute in the node itself rather than in the web browser.

Components can:

* Store data securely in the peer, suitable for private keys - that only they can read. 
  * This is similar to the browser's cookie or local storage mechanisms but with better encryption and backup support.
  * As with local storage - a component can only access its own private data
* Communicate with the peer to retrieve, insert, and modify contracts and their state.
* Communicate with in-browser applications via a messaging mechanism that ties an application's messages to its key in Locutus
* Communicate with the user through a mechanism outside the web browser, eg. to approve a request from an application to sign something with the component's private key
  * The specifics of this will depend on the OS, perhaps using the OS's existing notification system, or a system tray icon on Windows

A Component implements the following interface:

```rust
trait Component {
  /// Process inbound messages, producing zero or more outbound messages in response
  /// Note that all state for the component must be stored using the secret mechanism
  fn process(messages : Vec<InboundComponentMsg>) -> Vec<OutboundComponentMsg>;
}

enum InboundComponentMsg {
  GetSecretResponse {
    key : Vec<u8>,
    value : Option<Vec<u8>>,
  }

  ApplicationMessage {
    from_app : Hash,
    payload : Vec<u8>,
  },

  GetContractResponse {
    contract_id : Vec<u8>,
    update_data : UpdateData, // See #167 
  }

  UserResponse {
    request_id : u32,
    response : String,
  }
}

enum OutboundComponentMsg {
  GetSecretRequest {
    key : Vec<u8>,
  } 

  SetSecretRequest {
    key : Vec<u8>,
    // Option::None will delete value associated with key
    value : Option<Vec<u8>>,
  }

  ApplicationMessage {
    to_app : Hash,
    payload : Vec<u8>,
  }

  GetContractRequest {
    mode : RelatedMode, // See #167 
    contract_id : Vec<u8>,
  }

  UserRequest {
    request_id : u32,

    /// A HTML fragment supporting a limited set of HTML tags, including hyperlinks
	message : String,

    /// If a response is required from the user they can be chosen from this list
    responses : Vec<String>,
  }
}
```

# Distribution of Components

Components are distributed via their contract; their webassembly and parameters are distributed as the state of a contract together with parameters - similar to applications. Components are identified by the keys of the contracts through which they're distributed.

An application can request the installation of a Component, this may require some interaction by the user, for example, to donate to validate an antiflood token generator.

## Outstanding questions / concerns

- [x] How to handle malicious Components, eg. that try to waste resources
- [x] How to handle internationalization for UserRequests since they contain human-readable text
- [x] Current user interaction is limited to questions with multiple-choice answers; this is probably too restrictive
- [x] Potentially add an "alarm clock" mechanism so the components can request to be woken up at a specific time
- [x] Can this be generalized in any way?
- [x] Components need a way to generate secure random data, eg. for keypair generation
- [x] Should #245 be implemented as a Component? What additional functionality would this require?

**Comment by iduartgomez** [comment]
An example on how this may be used by the email application:
```
Email Decentralized App

User gets contract key of email application, visits it in web browser via proxy
Create public/private keypair to represent this user’s inbox
Does the app create the keypair, or does the component create it on initialization?
Application requests that node create component to store and manage access to private key
Application requests component creation, provides component wasm code + parameters
Application and component are aware of each-other so they can trust messages received from the other
Node can assure application and component that they’re talking to each other
User wants to send an email
Composes email using application UI, hits “send”
Application sends message to component requesting that the component sign it, which the component does because it knows and trusts the application
Application adds signed message to inbox contract of the intended recipient (after obtaining a antiflood token)

—-------------------

Email application installed
App requests creation of email component to store private key
App sends message to component:
App — [CreateInboxRequest] → Component
Component —- [SetSecret(“inbox_key”, private_key)] —> NODE
Component — [CreateInboxResponse(publicKey)] —> App
—- app wants to send an email
App — [PleaseSignMessage(message_content)] —> Componen
Component —- [GetSecretRequest(“inbox_key”)] —-> Node
Node —- [GetSecretResponse(“inbox_key”, private_key)] —> Component
Component —- [MessageSigned(signature)] —> App
```

**Comment by iduartgomez** [comment]
Note to self:
- Add a registering command for new components
- On the API on the node provide a call for requesting secure random bytes
  - This takes care of the item: "Components need a way to generate secure random data, eg. for keypair generation"
- When components are created (before registering), the necessary keys are generated and provided by the source of the component (via the API).
- The current interface is very generic, we are not expecting any certain template for user interaction and just dealing with raw bytes we can force this later on (potentially separating content from representation so we don't end up trapping ourselves with an implementation like HTML)
  - re. "Current user interaction is limited to questions with multiple-choice answers; this is probably too restrictive"
  - before we are done with this issue we need at least to implement one working version of this though; my general idea is to decompose the content/values (we will be sending those in some standard format in the messages, something like a json) from how they are represented (notifications channels can be registered in the node on initialization, this will make it easier to use different kinds of channels based on the platform, user preferences, etc.). The notification channels will have to be able to implement a certain interface (like receiving messages, etc.). Need to define this better.

**Comment by iduartgomez** [comment]
Some additional changes that we will have to take ind mind:
- [ ] Limit the creation of components per application to 10mb (by default, configurable) worth of secrets stored.
- [ ] Ask for confirmation before deleting any secrets because of lack of space, since it contains sensible data (like private keys).
- [ ] Add versioning.
- [x] In the future, take in mind any synchronization problems that may happen when using a distributed system as the location where secrets are stored.

**Comment by iduartgomez** [comment]
We can close this as we have a sample test component now in `main`, most remaining changes have to do with fleshing out the API and will be fixed when we move to flatbuffers.
