### ISSUE TITLE
README.md improvements

### ISSUE THREAD

**Issue by sanity** [freenet/locutus#296]
@iduartgomez's suggestions:

- [x] add the link to the documentation pretty much at the top of the readme, like they do here https://github.com/rust-lang/cargo (we can name it "The Locutus Book" too). 
- [x] Add a badge to our autogenerated API docs, eg https://github.com/launchbadge/sqlx. we should be pointing to https://docs.rs/locutus/0.0.2/locutus/ , will be improving the crate docs next 
- [x] Maybe for some sections we should be pointing to other resource (either in the book or in the wiki), so the readme doesn't get too long, like the "News" section (or only leave the most recent news and point to a wiki/book page for older news)
- [x] on that vein, I think the detailed info (sections 2 & 3) should reside in the book too 
- [x] if pointing to the book should be the first thing, add an other section which is "additional resources" and link the YouTube videos there. Also in the book, on the introduction page, have a subsection which is "additional resources" and does the same

**Comment by iduartgomez** [comment]
I think all changes are done (more or less) :)
