### ISSUE TITLE
ContractInterface::get_state_delta() should return a Result

### ISSUE THREAD

**Issue by sanity** [freenet/locutus#299]
Removed this from `get_state_delta()` function in `interface.rs`, not sure if it's still relevant, close if not.

```
    // FIXME: should return a result type, instead
```

**Comment by iduartgomez** [comment]
Yes this still has to be done, but the change is not trivial since requires some juggling with pointers etc. and need to make sure we are making things correctly.

**Comment by iduartgomez** [comment]
Closing as I am tackling this changes in #167
