### ISSUE TITLE
Update status in README

### ISSUE THREAD

**Issue by remram44** [freenet/locutus#368]
The current README says to expect an update in the past, which is not a great look. This seems to still be developed, so it's probably just a matter of updating the date:

> We're working hard and expect an early prototype in August 2022.

**Comment by iduartgomez** [comment]
Yeah this was very optimistic, since we keep adding (necessary) complexity and changing goals. I would avoid mentioning any concrete dates, and instead just mention that a prototype is work-in-progress and should be releases "Soon (tm)" (when is done).

**Comment by sanity** [comment]
@remram44 Thanks for the heads-up, fixed now.
