### ISSUE TITLE
I2p tor freenet vpn all are controlled and belong to the same globalists

### ISSUE THREAD

**Issue by vssasks** [freenet/locutus#538]
His description is wrong. From the very beginning internet was implemented by the world jewelry on instructions from handfull of globals. Internet has never been free. It was aimed at more control than tv, press, music and cinema could propose. Freenet is just another project from j leading to nowhere. Don't waste time on it...

**Comment by iduartgomez** [comment]
This is not a technical issue, please keep issues on point to technical issues. For everything else `Discussions`or public forums.

**Comment by krionical** [comment]
I've never seen a git issue about "global world conspiracy" on a project before, let alone it being closed!
