### ISSUE TITLE
Manual "Architecture" page contains incorrect hyperlink

### ISSUE THREAD

**Issue by solipsis-project** [freenet/locutus#540]
https://docs.freenet.org/architecture.html contains a link to https://github.com/freenet/locutus/blob/f1c8075e173f171c17ffa8d08803b2c9aea4ddf3/modules/antiflood-tokens/contracts/token-allocation-record/src/lib.rs#L10 when it probably wants to link to https://github.com/freenet/locutus/blob/f1c8075e173f171c17ffa8d08803b2c9aea4ddf3/crates/locutus-stdlib/src/contract_interface.rs#L424 instead. That is, it should link to the interface definition instead of an arbitrary implementer of that interface.

**Comment by iduartgomez** [comment]
@sanity this no longer applies, but we are instead linking to a wrong commit so needs fixing nevertheless.
