### ISSUE TITLE
document crypto algorithms for end user

### ISSUE THREAD

**Issue by khimaros** [freenet/locutus#833]
_Originally posted by @iduartgomez in https://github.com/freenet/locutus/issues/429#issuecomment-1691986259_

> So here is a list of algorithms we are currently using and actions I am thinking we could take, considering things like ergonomics, maturity of available implementations, etc.:
> - P384 for identities. Not doing much with this yet but would be used for signatures where public key signing is not necessary (so where RSA is not needed) or key agreements.
> - ChaCha20-Poly1305 for symmetric encryption -> ??? Could change for AES, worth it though.
> - Blake3 , for computing hashes of things like contracts -> None.
> - RSA with 4096 bytes size for asymmetric encryption -> None.
> - SHA256 for digests of signatures -> Could replace for SHA3-512/256.
>
> My biggest question right now is what could we use for symmetric encryption. I choose chacha20 because it's performance for pure software implementations (without adequate hardware support) is usually faster than AWS, and the secutiry level is similar, but since we want to support multiple targets, which may not have proper hardware acceleration chacha20 seems like a good candidate.
> 
> FYI @sanity

**Comment by ple1n** [comment]
I don't think it's worth opening an issue for this detail, as it will be done at some point eventually. And it's trivial to check for the ciphers being used.

**Comment by sanity** [comment]
Yes, I'm not sure why this requires a separate issue.
